### ISSUE TITLE
Can't start automatically on qtile

### ISSUE THREAD

**Issue by unamiral** [thomas10-10/foo-Wallpaper-Feh-Gif#15]
**Can't start automatically on qtile**
I tried to start the app in the startup, but it's doesn't work and get me a **blank background**. 
I tried put command in `.xprofile` , in autostart hook of qtile but all of this, Doesn't work :(
I need help!

**Comment by elapse-d** [comment]
i have read http://docs.qtile.org/en/latest/manual/config/hooks.html?highlight=start#autostart
and i put in my autostart.sh 


```
#!/bin/bash 
pkill -f back4.sh
~/.back4 0.010 gif.gif &
```

chmod +x autostart.sh


it's work for me

**Comment by unamiral** [comment]
Thanks!
