### ISSUE TITLE
not working ı dont know how ı explain

### ISSUE THREAD

**Issue by ghost** [thomas10-10/foo-Wallpaper-Feh-Gif#16]
cd ~
chmod +x back4.sh
./back4.sh 0.010 gif/pixel.gif & and 
![2021-12-30-192945_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/147770403-c9a41d35-ef7a-432d-a615-9b266c7396ea.png)

![2021-12-30-193307_914x88_scrot](https://user-images.githubusercontent.com/80429360/147770540-5ed22e5e-e2f8-48f5-b9e9-e616cec7aeb7.png)

**Comment by elapse-d** [comment]
feh is installed ?
