### ISSUE TITLE
Don't seem to work on PopOS

### ISSUE THREAD

**Issue by gnomo223** [thomas10-10/foo-Wallpaper-Feh-Gif#17]
I'm using the newer version of PopOS to this date, wo is ubuntu based. Also i'm following all the instructions but it didn't seem to do any changes, if i do `ps -e` it shows nothing, didn't see a option for debug as well, so i cannot explain as good as i wanted, maybe with a diferent os it'll work.

**Comment by gnomo223** [comment]
> I'm using the newer version of PopOS to this date, wo is ubuntu based. Also i'm following all the instructions but it didn't seem to do any changes, if i do `ps -e` it shows nothing, didn't see a option for debug as well, so i cannot explain as good as i wanted, maybe with a diferent os it'll work.

Actually, reading the man page for feh it tells that doesn't work with GNOME enviroments, so that option will not work anyways, ive tried xwallpaper but with none results. Will keep trying...

xwallpaper gave me `[dorobo@pc-da-xuxa ~]$ xwallpaper --debug --zoom '/home/dorobo/Imagens/361273e3467859b48eab0ef7fa3610dd.jpg' 
Chamada de sistema inválida (imagem do núcleo gravada)`
Translating will be like "bad system call (core dumped)", tried other options with no luck, think that's it for today.

**Comment by elapse-d** [comment]
it's work with `gsettings set org.gnome.desktop.background picture-uri file:////home/dorobo/Imagens/361273e3467859b48eab0ef7fa3610dd.jpg` ?

**Comment by elapse-d** [comment]
I have implemented gsettings, but the animation is not really great compared to feh
