### ISSUE TITLE
Not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by AccountOneOff** [thomas10-10/foo-Wallpaper-Feh-Gif#2]
Hey cool stuff! Unfortunately this doesn't work for me.

This is all I get when running the script. No errors but the wallpaper never changes. I do see `/tmp/back4` was created.

- Ubuntu 18.04
- Gnome 3.28.3
- feh version 2.23.2

```
cxf@PC:~$ cd foo-Wallpaper-Feh-Gif/
cxf@PC:~/foo-Wallpaper-Feh-Gif$ ./back4.sh gif/cyberpunk.gif-0.010 &
[1] 2838
cxf@PC:~/foo-Wallpaper-Feh-Gif$ spliting ..
ok
cxf@PC:~/foo-Wallpaper-Feh-Gif$

**Comment by Z-Mullen** [comment]
feh does not support changing the background on gnome, so this script won't work.

**Comment by AccountOneOff** [comment]
Aww that's too bad. Thanks.

**Comment by joshuah345** [comment]
so it doesnt support xfce either. What does it support?

**Comment by elapse-d** [comment]
hey i will search for an alternative
More news soon.

**Comment by elapse-d** [comment]
Originally it support wm like I3,iwm,awesome ..

Solution for ubuntu/xfce ->
In back4.sh change this pattern
`feh --bg-fill $dir/$hash/$i`
by
`xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -s $dir/$hash/$i`


You can set style stretched in your desktop panel

Let me hear from you.
