### ISSUE TITLE
How do i put the script autostart in i3 wm

### ISSUE THREAD

**Issue by ahloiscreamo** [thomas10-10/foo-Wallpaper-Feh-Gif#3]
Hi there,

Thanks for the awesome tool.
i have a question,

i want to make the script autostart in i3 login.

i put the script on bin and try to exec it on i3 conf.
but its not working,
Do you know how to.

**Comment by ahloiscreamo** [comment]
I see youre looking for feh alt.
This [lightweight image program](https://github.com/muennich/sxiv) (recommended for tiling wm)
can open gif by default 
would you like to implement it ?

**Comment by elapse-d** [comment]
i will search for the best solution for autostart, thanks i will look that

**Comment by elapse-d** [comment]
for autostart, in your i3 config , append  : 
`exec_always --no-startup-id killall back4.sh`
`exec_always --no-startup-id $HOME/back4.sh 0.03 Downloads/beautycity.gif`

**Comment by ahloiscreamo** [comment]
Hi there,
thanks for the guide, work like a charm!
i'll close the issues,

**Comment by ghost** [comment]
> for autostart, in your i3 config , append : `exec_always --no-startup-id killall back4.sh` `exec_always --no-startup-id $HOME/back4.sh 0.03 Downloads/beautycity.gif`

Hello. These commands doesn't work for me, example when i restart i3 the gif gets faster and faster. So I created a launch script inspired by [polybar's launch script](https://github.com/polybar/polybar/wiki#launching-the-bar-in-your-wms-bootstrap-routine) and it works. It doesn't get faster and faster when restarting i3.

Here is launch script:
```
#!/usr/bin/env bash

kill -9 `pgrep -f back4.sh`

echo "---" | tee -a /tmp/back4-1.log
$HOME/.local/bin/back4.sh auto $HOME/.gifs/6.gif | tee -a /tmp/back4-1.log & disown

echo "Must be fine!"
```

In i3 config, I added that command below to run back4.sh:
```
exec_always --no-startup-id $HOME/.local/bin/launch.sh &
```
In this way the gif doesn't get faster and faster.

Thank you for your time.
